services:
  backend:
    container_name: backend-c
    environment:
      - POSTGRES_HOST=database-c
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=todoapp
    build:
      context: .
      args:
        bin_to_build: httpserver
    ports:
      - 8080:8080
    networks:
      - web
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database-c
    environment:
      - POSTGRES_HOST=database-c
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=todoapp
    image: postgres:17
    volumes:
      - ./testing/testdata/init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - database-v:/var/lib/postgresql/data
    networks:
      - web
    healthcheck:
      test: pg_isready -U postgres -d todoapp
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  backend-v:
    name: "backend-v"
  database-v:
    name: "database-v"

networks:
  web:
    driver: bridge
